### ISSUE TITLE
files: in local dev, Transfers aren't being merged or uploaded

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#200]
A few users have reported seeing Transfers not being merged (in `storage/merged/`) or uploaded to the remote FTP/SFTP server. This is a problem because it limits the effectiveness of our demo for new users of our platform.

**Comment by adamdecaf** [comment]
The solutions (for local dev) are multi-fold. We need to configure paygate to upload much smaller files (after only a couple transfers) and to merge/upload more often.

**Comment by rayjlinden** [comment]
These improvements are certainly helpful!  However, an end point to "flush" files to sftp would actually aid testing even more.  Otherwise, tests still have to "sleep" some amount of time to ensure files have been pushed.  A flush method would allow automated to run faster and be less brittle because it would have a more direct way of know all transactions should be reflected in an ftp site.

**Comment by adamdecaf** [comment]
I've been thinking about that. It would be an admin endpoint (`POST :9092/files/upload`) and we could accept an optional parameter `overLineCount=N` to only force files larger than N lines. (Default would be without that param and a LoC of 1)
